/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio1;


import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class menuEj1 extends javax.swing.JFrame {
    DefaultListModel<Tarea>listaTareasCompletadas; // modelo de la lista
    DefaultListModel<Tarea>listaTareasPendientes;  // no confundir con la lista
    List<Tarea>listaTareas=new ArrayList<>();
    ButtonGroup grupoBotones=new ButtonGroup();
    /**
     * Creates new form menuEj1
     */
    public menuEj1() {
        initComponents();
        listaTareasCompletadas=new DefaultListModel<>();
        listaTareasPendientes=new DefaultListModel<>();
        jlistTareasCompletadas.setModel(listaTareasCompletadas);
        jLisTareasPendientes.setModel(listaTareasPendientes);
        grupoBotones.add(radidoButtonCompletada);
        grupoBotones.add(radioButtonPendiente);
        radioButtonPendiente.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jNombreTarea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistTareasCompletadas = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLisTareasPendientes = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBotonEliminarTarea = new javax.swing.JButton();
        jBotonCompletarTarea = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radidoButtonCompletada = new javax.swing.JRadioButton();
        radioButtonPendiente = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de tareas");

        jLabel1.setText("Tarea");

        jLabel2.setText("Estado");

        jlistTareasCompletadas.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jlistTareasCompletadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistTareasCompletadas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistTareasCompletadasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistTareasCompletadas);

        jButton1.setText("Agregar Tarea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLisTareasPendientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLisTareasPendientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLisTareasPendientesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jLisTareasPendientes);

        jLabel3.setText("Tareas Completadas");

        jLabel4.setText("Tareas Pendientes");

        jBotonEliminarTarea.setText("Eliminar Tarea");
        jBotonEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEliminarTareaActionPerformed(evt);
            }
        });

        jBotonCompletarTarea.setText("Completa Tarea");
        jBotonCompletarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCompletarTareaActionPerformed(evt);
            }
        });

        jLabel5.setText("Tareas Totales 0");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Lista de tareas");

        radidoButtonCompletada.setText("Completada");

        radioButtonPendiente.setText("Pendiente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioButtonPendiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radidoButtonCompletada)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(141, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 125, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGap(36, 36, 36))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addComponent(jBotonEliminarTarea)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBotonCompletarTarea))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(127, 127, 127)
                                    .addComponent(jLabel5)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radidoButtonCompletada)
                    .addComponent(radioButtonPendiente))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBotonEliminarTarea)
                        .addComponent(jBotonCompletarTarea))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel5)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
         String nombreTarea=jNombreTarea.getText();
         if(nombreTarea.isEmpty()){
            throw new RuntimeException("Tarea vacia");
         }
         String estado;
         Tarea tarea;
        if(radidoButtonCompletada.isSelected()){
            estado="Completado";
            tarea=new Tarea(nombreTarea, estado);
            listaTareasCompletadas.addElement(tarea);
           
        }else{
            estado="Pendiente";
            tarea=new Tarea(nombreTarea, estado);
            listaTareasPendientes.addElement(tarea);
        }
        
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this,"La tarea no puede estar vacia","Advertencia!!",JOptionPane.WARNING_MESSAGE);
            jNombreTarea.setText("");
        }
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlistTareasCompletadasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistTareasCompletadasValueChanged
        // TODO add your handling code here:
         if (!evt.getValueIsAdjusting()) {
        if (!jlistTareasCompletadas.isSelectionEmpty()) {
            jLisTareasPendientes.clearSelection();
        }
    }
        
        
        //otra manera
//        
//      if(!evt.getValueIsAdjusting()){
//        if (evt.getSource() == jlistCompletadas) {
//            jlistPendientes.clearSelection();
//        } else if (evt.getSource() == jlistPendientes) {
//            jlistCompletadas.clearSelection();
//        }
//        }  

        
        
    }//GEN-LAST:event_jlistTareasCompletadasValueChanged

    private void jBotonEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEliminarTareaActionPerformed
        // TODO add your handling code here:
        Tarea valorCompletada=jlistTareasCompletadas.getSelectedValue(); // obtiene el valor  seleccionado de la lista
     
        if(valorCompletada!=null){
            listaTareasCompletadas.removeElement(valorCompletada);
            
        }
       Tarea valorPendiente=jLisTareasPendientes.getSelectedValue();
        if(valorPendiente!=null){
            listaTareasPendientes.removeElement(valorPendiente);
        }
    }//GEN-LAST:event_jBotonEliminarTareaActionPerformed

    private void jBotonCompletarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCompletarTareaActionPerformed
        // TODO add your handling code here:
        if(!jLisTareasPendientes.isSelectionEmpty()){
            Tarea tareaPendiente=jLisTareasPendientes.getSelectedValue();
            String nombreTarea=tareaPendiente.getTarea();
            listaTareasPendientes.removeElement(tareaPendiente);
            listaTareasCompletadas.addElement(new Tarea(nombreTarea,"Completada")); 
        }
    }//GEN-LAST:event_jBotonCompletarTareaActionPerformed

    private void jLisTareasPendientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLisTareasPendientesValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
        if (!jLisTareasPendientes.isSelectionEmpty()) {
            jlistTareasCompletadas.clearSelection();
        }
    }
        
//         if(!evt.getValueIsAdjusting()){
//        if (evt.getSource()== jlistPendientes){
//             jlistCompletadas.clearSelection();
//         }else if (evt.getSource()== jlistCompletadas){
//             jlistPendientes.clearSelection();
//         }
//    }   
        
    }//GEN-LAST:event_jLisTareasPendientesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuEj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuEj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuEj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuEj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menuEj1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonCompletarTarea;
    private javax.swing.JButton jBotonEliminarTarea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<Tarea> jLisTareasPendientes;
    private javax.swing.JTextField jNombreTarea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Tarea> jlistTareasCompletadas;
    private javax.swing.JRadioButton radidoButtonCompletada;
    private javax.swing.JRadioButton radioButtonPendiente;
    // End of variables declaration//GEN-END:variables

}

